/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IQuoterV2 } from './IQuoterV2.js';
export type { IUniversalRouter } from './IUniversalRouter.js';