/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'FlashSwap', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FlashSwap__factory>
getContractFactory(name: 'IQuoterV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IQuoterV2__factory>
getContractFactory(name: 'IUniversalRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniversalRouter__factory>
getContractFactory(name: 'MockPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockPool__factory>
getContractFactory(name: 'MockPoolAddressesProvider', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockPoolAddressesProvider__factory>

  getContractAt(name: 'FlashSwap', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FlashSwap>
getContractAt(name: 'IQuoterV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IQuoterV2>
getContractAt(name: 'IUniversalRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniversalRouter>
getContractAt(name: 'MockPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockPool>
getContractAt(name: 'MockPoolAddressesProvider', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockPoolAddressesProvider>

  deployContract(name: 'FlashSwap', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FlashSwap>
deployContract(name: 'IQuoterV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IQuoterV2>
deployContract(name: 'IUniversalRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniversalRouter>
deployContract(name: 'MockPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPool>
deployContract(name: 'MockPoolAddressesProvider', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPoolAddressesProvider>

  deployContract(name: 'FlashSwap', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FlashSwap>
deployContract(name: 'IQuoterV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IQuoterV2>
deployContract(name: 'IUniversalRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniversalRouter>
deployContract(name: 'MockPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPool>
deployContract(name: 'MockPoolAddressesProvider', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPoolAddressesProvider>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  