/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockPool } from './MockPool.js';
export type { MockPoolAddressesProvider } from './MockPoolAddressesProvider.js';