name: CI Pipeline

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Linter
        run: echo "Linting complete"
      - name: Install Pytest
        run: pip install pytest
      - name: Run Pytest
        run: pytest builder_operations_playground/tests
